export default {
    es: {
        'About me': 'Acerca de mi',
        'Hi! Thanks for reading my resume!': '¡Hola! ¡Gracias por leer mi curriculum!',
        'So, here\'s a little about me... I love solving problems! Whether it\'s about programming, logic games, or anything I have to put my mind to solve, I love it. I\'m passionate about what I do, and I love learning new stuff. I\'m proactive, always trying to figure out ways to improve my work.': 'Un poco sobre mi... ¡Me encanta resolver problemas! Ya sea sobre programación, juegos de lógica, o cualquier cosa que tenga que pensar para resolver, me encanta. Soy apasionado por lo que hago, y me encanta aprender cosas nuevas. Soy proactivo, siempre trato de encontrar formas de mejorar mi trabajo.',
        'I\'m also all for automation, I try all the time to find ways to automatize my work (hey, I even developed this resume in React so it\'s easier for me to update it\'s info! You can check out the source code in {GithubRepoLink})': 'También me encanta la automatización, trato todo el tiempo de encontrar formas de automatizar mi trabajo (¡hasta desarrollé este curriculum en React para que me sea más fácil actualizar la información! Podés ver el código fuente en {GithubRepoLink})',
        'I try to write the cleanest code I can, even taking time to figure out how to improve its readability, and trying to follow coding conventions according to the language I\'m using.': 'Trato de escribir el código lo más limpio que puedo, incluso tomándome tiempo para encontrar formas de mejorar su legibilidad, y tratando de seguir las convenciones de codificación según el lenguaje que estoy usando.',
        'I like functional programming, because of its way to approach problems and finding solutions, and it being close to mathematical theory; I like [to learn] theoretical knowledge, understand the fundamentals of things, because I think it helps you finding better solutions, but without forgetting of being pragmatic when it comes to making things work.': 'Me gusta la programación funcional, por el enfoque que tiene sobre los problemas y sobre encontrar soluciones, y por su cercanía a la teoría matemática; me gusta [aprender] el conocimiento teórico, entender los fundamentos, porque creo que ayuda a encontrar mejores soluciones, pero no me olvido de ser pragmático cuando se trata de hacer que las cosas funcionen.',
    },
};
